name = "etouch-pos"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "etouch-pos-db"
database_id = "74df62b3-e3ff-4ec5-a726-a8112563b2f6"
